[colors.primary]
background = '#18120f'
foreground = '#ede0da'

[colors.selection]
text = '#ede0da'
background = '#8f5330'

[colors.cursor]
text = '#18120f'
cursor = '#ffb68f'

[colors.normal]
black   = '#18120f'
red     = '#ff7872'
green   = '#96ff7f'
yellow  = '#ffe572'
blue    = '#f29f72'
magenta = '#763816'
cyan    = '#ffb68f'
white   = '#fff5ef'

[colors.bright]
black   = '#a59d99'
red     = '#ffa39f'
green   = '#b6ffa5'
yellow  = '#ffeea5'
blue    = '#ffc09f'
magenta = '#ffcbb0'
cyan    = '#ffdecc'
white   = '#fffaf8'
