[colors.primary]
background = '#181210'
foreground = '#ede0db'

[colors.selection]
text = '#ede0db'
background = '#7e4729'

[colors.cursor]
text = '#181210'
cursor = '#ffb691'

[colors.normal]
black   = '#181210'
red     = '#e0487f'
green   = '#99d66e'
yellow  = '#dbac7b'
blue    = '#bc6d44'
magenta = '#bf937d'
cyan    = '#ffb691'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f91'
green   = '#abe086'
yellow  = '#e8c097'
blue    = '#ffc39b'
magenta = '#b46353'
cyan    = '#997250'
white   = '#ffffff'
