# List of pluginsetw -g mouse on

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dracula/tmux'
set -s default-terminal 'xterm'

# dracula customizations
set -g @dracula-plugins "battery weather time"
set -g @dracula-show-powerline true
set -g @dracula-show-fahrenheit false
set -g @dracula-military-time true

run '~/.tmux/plugins/tpm/tpm'
set -g mouse on
# set prefix key to Ctrl-a
unbind-key C-b
set-option -g prefix C-a

# control automatic window renaming
setw -g automatic-rename off

# enable wm window titles
set -g set-titles on
